# Horizontal Pod Autoscaler (HPA) example configuration for Kubernetes.
# This HPA scales the sample-deployment based on CPU and memory usage metrics.

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-hpa
  namespace: default
spec:
  scaleTargetRef:
    # Reference to the deployment we want to scale.
    apiVersion: apps/v1
    kind: Deployment
    name: sample-deployment
  minReplicas: 2   # Minimum number of replicas that HPA will maintain.
  maxReplicas: 10  # Maximum number of replicas to which HPA can scale up.
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Target 70% CPU usage