# Horizontal Pod Autoscaler (HPA) for the worker Deployment
# Adjusts the number of replicas based on CPU utilization thresholds.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker  # Name of the deployment to scale
  minReplicas: 1  # Minimum number of Pods
  maxReplicas: 5  # Maximum number of Pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Target average CPU utilization per Pod